export const AUTHENTICATE_LOGIN = 'AUTHENTICATE_LOGIN';
export type AUTHENTICATE_LOGIN = typeof AUTHENTICATE_LOGIN;

export const AUTHENTICATING = 'AUTHENTICATING';
export type AUTHENTICATING = typeof AUTHENTICATING;