export { default as MainHeader } from './MainHeader/MainHeader';
export { default as MainFooter } from './MainFooter/MainFooter';
export { default as Carousel } from './Carousel/Carousel';
export { default as SuccessCard } from './Cards/SuccessCard';
export { default as MainContainer } from './MainContainer/MainContainer';
export { default as WhiteContainer } from './MainContainer/WhiteContainer';
export { default as ProjectContainer } from './ProjectContainer/ProjectContainer';
export { default as InputBox } from './Forms/InputBox';
export { default as Button } from './Forms/Button';
export { default as RadioBox } from './Forms/RadioBox';
export { default as RadioBoxGroup } from './Forms/RadioBoxGroup';
export { default as CheckBox } from './Forms/CheckBox';
export { default as SelectBox } from './Forms/SelectBox';
// export { default as TabcardDetails } from './Cards/IocprojectCard';